source 'https://github.com/coderMyron/LMYSpecs.git'

use_frameworks!

platform :ios, '9.0'

target 'LMYPersonInfoKit_Example' do
  pod 'CTMediator'
  pod 'LMYPersonPeferenceKit'
  pod 'LMYPersonInfoKit', :path => '../'

  

  target 'LMYPersonInfoKit_Tests' do
    inherit! :search_paths

    
  end
end
